### ISSUE TITLE
Awesome! Can you add a license please?

### ISSUE THREAD

**Issue by pburkholder** [mikeehsu/PsArmResources#1]
We're finding this library really useful. We have some pull requests we'd like to make. Can you please add a license so we can be clear that our contributions remain open-source?

Thanks!

-Peter

**Comment by thecapacity** [comment]
I for one would recommend CC0 - https://creativecommons.org/share-your-work/public-domain/cc0/

But you may have your own preferences thoughts

**Comment by mikeehsu** [comment]
Thanks for adding in the license.
